blank_issues_enabled: false
contact_links:
  - name: Часто задаваемые вопросы
    url: https://water-faq.github.io/OgibArm/faq.html
    about: Перед созданием обращения проверьте ответы на типичные вопросы.
